### ISSUE TITLE
Paasar tu presentación al README

### ISSUE THREAD

**Issue by francohilt** [pdep-utn-frd/23-bienvenidos-GonzaCrespin#1]
Hola...En vez de agregar un archivo podes directamente crear un readme y poner lo mismo que pusiste, con eso podes lograr que apenas se ingresa a tu presentación se visualize sin tener que ingresar al archivo.

**Comment by GonzaCrespin** [comment]
No sabia que en el nombre "README" hacia que cumpliera la función de verlo al entrar al repositorio. Ya lo corregí.
